server {
    listen 80 default_server;
    listen 443 ssl default_server;
    
    # Il server risponderà a QUALSIASI dominio, IP o localhost
    server_name _;

    ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
    ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;

    # Impostazioni per aumentare i limiti di upload (nel caso ci siano file pesanti o video)
    client_max_body_size 500M;

    location / {
        proxy_pass http://app:3003;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }
}
